from domain.enums import Criticite, LotTechnique

CHECKLIST_V1 = [
    {
        "controle_id": "DOC_001",
        "lot": LotTechnique.DOCUMENTATION,
        "section": "Documentation",
        "libelle": "Présence et conformité du schéma d'exécution",
        "reference": "Référentiel interne OPT'HELIOS",
        "criticite_par_defaut": Criticite.MAJEURE,
        "recommandation": "Fournir ou mettre à jour le schéma d'exécution.",
        "impact": "Réduit la maintenabilité et la capacité de diagnostic.",
    },
    {
        "controle_id": "DOC_002",
        "lot": LotTechnique.ELECTRICITE,
        "section": "Électricité",
        "libelle": "Présence et conformité du schéma électrique",
        "reference": "Référentiel interne OPT'HELIOS",
        "criticite_par_defaut": Criticite.MAJEURE,
        "recommandation": "Compléter ou corriger le schéma électrique.",
        "impact": "Limite l'exploitation et le dépannage de l'installation.",
    },
    {
        "controle_id": "CAP_001",
        "lot": LotTechnique.CAPTEURS,
        "section": "Champ capteurs / toiture",
        "libelle": "Supports capteurs conformes et fixés",
        "reference": "Référentiel interne OPT'HELIOS",
        "criticite_par_defaut": Criticite.CRITIQUE,
        "recommandation": "Reprendre la fixation et vérifier la conformité des supports.",
        "impact": "Risque mécanique et atteinte à la sécurité de l'installation.",
    },
    {
        "controle_id": "HYD_001",
        "lot": LotTechnique.HYDRAULIQUE,
        "section": "Hydraulique solaire",
        "libelle": "Circulation capteurs / échangeur dans le bon sens",
        "reference": "Référentiel interne OPT'HELIOS",
        "criticite_par_defaut": Criticite.CRITIQUE,
        "recommandation": "Corriger le sens de circulation hydraulique.",
        "impact": "Altération majeure du fonctionnement thermique.",
    },
    {
        "controle_id": "HYD_004",
        "lot": LotTechnique.SECURITE,
        "section": "Hydraulique solaire",
        "libelle": "Présence d'une soupape de sécurité conforme",
        "reference": "Référentiel interne OPT'HELIOS",
        "criticite_par_defaut": Criticite.CRITIQUE,
        "recommandation": "Installer ou remplacer la soupape de sécurité conforme.",
        "impact": "Risque de surpression et défaut de sécurité.",
    },
    {
        "controle_id": "EXP_001",
        "lot": LotTechnique.EXPANSION,
        "section": "Système d'expansion",
        "libelle": "Vase d'expansion dimensionné et adapté",
        "reference": "Référentiel interne OPT'HELIOS",
        "criticite_par_defaut": Criticite.CRITIQUE,
        "recommandation": "Vérifier et corriger le dimensionnement du vase d'expansion.",
        "impact": "Instabilité hydraulique et risque de dysfonctionnement majeur.",
    },
    {
        "controle_id": "STO_001",
        "lot": LotTechnique.ECHANGEUR_STOCKAGE,
        "section": "Échangeur / stockage",
        "libelle": "Échangeur raccordé en contre-courant",
        "reference": "Référentiel interne OPT'HELIOS",
        "criticite_par_defaut": Criticite.MAJEURE,
        "recommandation": "Revoir le raccordement de l'échangeur.",
        "impact": "Échange thermique dégradé.",
    },
    {
        "controle_id": "ECS_001",
        "lot": LotTechnique.ECS_BOUCLAGE,
        "section": "Distribution ECS / bouclage",
        "libelle": "Mitigeur thermostatique présent",
        "reference": "Référentiel interne OPT'HELIOS",
        "criticite_par_defaut": Criticite.MAJEURE,
        "recommandation": "Installer un mitigeur thermostatique adapté.",
        "impact": "Risque de non-maîtrise de la température d'ECS.",
    },
    {
        "controle_id": "MET_001",
        "lot": LotTechnique.METROLOGIE,
        "section": "Métrologie / tests",
        "libelle": "Manomètre de contrôle du circuit solaire présent",
        "reference": "Référentiel interne OPT'HELIOS",
        "criticite_par_defaut": Criticite.MAJEURE,
        "recommandation": "Installer un manomètre de contrôle fiable et accessible.",
        "impact": "Suivi hydraulique insuffisant.",
    },
    {
        "controle_id": "CPT_001",
        "lot": LotTechnique.COMPTEURS,
        "section": "Compteurs énergétiques",
        "libelle": "Compteur d'énergie solaire ESU présent et exploitable",
        "reference": "Référentiel interne OPT'HELIOS",
        "criticite_par_defaut": Criticite.MAJEURE,
        "recommandation": "Installer ou remettre en service le compteur ESU.",
        "impact": "Production solaire non quantifiable.",
    },
]